sonar.organization=manish-9245
sonar.projectKey=manish-9245_collabpro
sonar.projectName=collabpro
sonar.sources=app,components,lib
sonar.exclusions=node_modules/**, .next/**, test-results/**, playwright-report/**, tests/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
