/**
 * Generated by scripts/generate-avatars.mjs - do not hand-edit.
 *
 * Profile page's "premium animated avatar" set: 60
 * DiceBear (CC0-licensed) illustrations, pre-rendered to static SVG files
 * under public/avatars/ with an animated gradient ring wrapped around each
 * one. Static files, not embedded data URIs - DiceBear itself is only a
 * devDependency and never ships in the client bundle.
 */
export interface AvatarPreset {
  id: string;
  name: string;
  url: string;
}

export const AVATAR_PRESETS: AvatarPreset[] = [
  {
    "id": "notionists-1",
    "name": "Notionists 1",
    "url": "/avatars/notionists-1.svg"
  },
  {
    "id": "notionists-2",
    "name": "Notionists 2",
    "url": "/avatars/notionists-2.svg"
  },
  {
    "id": "notionists-3",
    "name": "Notionists 3",
    "url": "/avatars/notionists-3.svg"
  },
  {
    "id": "notionists-4",
    "name": "Notionists 4",
    "url": "/avatars/notionists-4.svg"
  },
  {
    "id": "notionists-5",
    "name": "Notionists 5",
    "url": "/avatars/notionists-5.svg"
  },
  {
    "id": "notionists-6",
    "name": "Notionists 6",
    "url": "/avatars/notionists-6.svg"
  },
  {
    "id": "notionists-7",
    "name": "Notionists 7",
    "url": "/avatars/notionists-7.svg"
  },
  {
    "id": "notionists-8",
    "name": "Notionists 8",
    "url": "/avatars/notionists-8.svg"
  },
  {
    "id": "notionists-9",
    "name": "Notionists 9",
    "url": "/avatars/notionists-9.svg"
  },
  {
    "id": "notionists-10",
    "name": "Notionists 10",
    "url": "/avatars/notionists-10.svg"
  },
  {
    "id": "notionists-11",
    "name": "Notionists 11",
    "url": "/avatars/notionists-11.svg"
  },
  {
    "id": "notionists-12",
    "name": "Notionists 12",
    "url": "/avatars/notionists-12.svg"
  },
  {
    "id": "notionists-13",
    "name": "Notionists 13",
    "url": "/avatars/notionists-13.svg"
  },
  {
    "id": "notionists-14",
    "name": "Notionists 14",
    "url": "/avatars/notionists-14.svg"
  },
  {
    "id": "notionists-15",
    "name": "Notionists 15",
    "url": "/avatars/notionists-15.svg"
  },
  {
    "id": "notionists-16",
    "name": "Notionists 16",
    "url": "/avatars/notionists-16.svg"
  },
  {
    "id": "notionists-17",
    "name": "Notionists 17",
    "url": "/avatars/notionists-17.svg"
  },
  {
    "id": "notionists-18",
    "name": "Notionists 18",
    "url": "/avatars/notionists-18.svg"
  },
  {
    "id": "notionists-19",
    "name": "Notionists 19",
    "url": "/avatars/notionists-19.svg"
  },
  {
    "id": "notionists-20",
    "name": "Notionists 20",
    "url": "/avatars/notionists-20.svg"
  },
  {
    "id": "notionists-21",
    "name": "Notionists 21",
    "url": "/avatars/notionists-21.svg"
  },
  {
    "id": "notionists-22",
    "name": "Notionists 22",
    "url": "/avatars/notionists-22.svg"
  },
  {
    "id": "notionists-23",
    "name": "Notionists 23",
    "url": "/avatars/notionists-23.svg"
  },
  {
    "id": "notionists-24",
    "name": "Notionists 24",
    "url": "/avatars/notionists-24.svg"
  },
  {
    "id": "notionists-25",
    "name": "Notionists 25",
    "url": "/avatars/notionists-25.svg"
  },
  {
    "id": "notionists-26",
    "name": "Notionists 26",
    "url": "/avatars/notionists-26.svg"
  },
  {
    "id": "notionists-27",
    "name": "Notionists 27",
    "url": "/avatars/notionists-27.svg"
  },
  {
    "id": "notionists-28",
    "name": "Notionists 28",
    "url": "/avatars/notionists-28.svg"
  },
  {
    "id": "notionists-29",
    "name": "Notionists 29",
    "url": "/avatars/notionists-29.svg"
  },
  {
    "id": "notionists-30",
    "name": "Notionists 30",
    "url": "/avatars/notionists-30.svg"
  },
  {
    "id": "shapes-1",
    "name": "Shapes 1",
    "url": "/avatars/shapes-1.svg"
  },
  {
    "id": "shapes-2",
    "name": "Shapes 2",
    "url": "/avatars/shapes-2.svg"
  },
  {
    "id": "shapes-3",
    "name": "Shapes 3",
    "url": "/avatars/shapes-3.svg"
  },
  {
    "id": "shapes-4",
    "name": "Shapes 4",
    "url": "/avatars/shapes-4.svg"
  },
  {
    "id": "shapes-5",
    "name": "Shapes 5",
    "url": "/avatars/shapes-5.svg"
  },
  {
    "id": "shapes-6",
    "name": "Shapes 6",
    "url": "/avatars/shapes-6.svg"
  },
  {
    "id": "shapes-7",
    "name": "Shapes 7",
    "url": "/avatars/shapes-7.svg"
  },
  {
    "id": "shapes-8",
    "name": "Shapes 8",
    "url": "/avatars/shapes-8.svg"
  },
  {
    "id": "shapes-9",
    "name": "Shapes 9",
    "url": "/avatars/shapes-9.svg"
  },
  {
    "id": "shapes-10",
    "name": "Shapes 10",
    "url": "/avatars/shapes-10.svg"
  },
  {
    "id": "shapes-11",
    "name": "Shapes 11",
    "url": "/avatars/shapes-11.svg"
  },
  {
    "id": "shapes-12",
    "name": "Shapes 12",
    "url": "/avatars/shapes-12.svg"
  },
  {
    "id": "shapes-13",
    "name": "Shapes 13",
    "url": "/avatars/shapes-13.svg"
  },
  {
    "id": "shapes-14",
    "name": "Shapes 14",
    "url": "/avatars/shapes-14.svg"
  },
  {
    "id": "shapes-15",
    "name": "Shapes 15",
    "url": "/avatars/shapes-15.svg"
  },
  {
    "id": "shapes-16",
    "name": "Shapes 16",
    "url": "/avatars/shapes-16.svg"
  },
  {
    "id": "shapes-17",
    "name": "Shapes 17",
    "url": "/avatars/shapes-17.svg"
  },
  {
    "id": "shapes-18",
    "name": "Shapes 18",
    "url": "/avatars/shapes-18.svg"
  },
  {
    "id": "shapes-19",
    "name": "Shapes 19",
    "url": "/avatars/shapes-19.svg"
  },
  {
    "id": "shapes-20",
    "name": "Shapes 20",
    "url": "/avatars/shapes-20.svg"
  },
  {
    "id": "shapes-21",
    "name": "Shapes 21",
    "url": "/avatars/shapes-21.svg"
  },
  {
    "id": "shapes-22",
    "name": "Shapes 22",
    "url": "/avatars/shapes-22.svg"
  },
  {
    "id": "shapes-23",
    "name": "Shapes 23",
    "url": "/avatars/shapes-23.svg"
  },
  {
    "id": "shapes-24",
    "name": "Shapes 24",
    "url": "/avatars/shapes-24.svg"
  },
  {
    "id": "shapes-25",
    "name": "Shapes 25",
    "url": "/avatars/shapes-25.svg"
  },
  {
    "id": "shapes-26",
    "name": "Shapes 26",
    "url": "/avatars/shapes-26.svg"
  },
  {
    "id": "shapes-27",
    "name": "Shapes 27",
    "url": "/avatars/shapes-27.svg"
  },
  {
    "id": "shapes-28",
    "name": "Shapes 28",
    "url": "/avatars/shapes-28.svg"
  },
  {
    "id": "shapes-29",
    "name": "Shapes 29",
    "url": "/avatars/shapes-29.svg"
  },
  {
    "id": "shapes-30",
    "name": "Shapes 30",
    "url": "/avatars/shapes-30.svg"
  }
];
