apiVersion: v1
kind: Secret
metadata:
  name: {{ include "collabpro.fullname" . }}-secrets
  labels:
    {{- include "collabpro.labels" . | nindent 4 }}
type: Opaque
data:
  # Base64 encoded sensitive keys
  database-url: {{ printf "postgresql://%s:%s@%s-postgres:%d/%s?schema=public" .Values.postgres.username .Values.postgres.password (include "collabpro.fullname" .) (.Values.postgres.servicePort | int) .Values.postgres.database | b64enc | quote }}
  redis-url: {{ printf "redis://%s-redis:%d" (include "collabpro.fullname" .) (.Values.redis.servicePort | int) | b64enc | quote }}
  smtp-password: {{ .Values.secretEnv.smtpPassword | b64enc | quote }}
