apiVersion: v1
kind: Service
metadata:
  name: {{ include "collabpro.fullname" . }}-web
  labels:
    {{- include "collabpro.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port.web }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "collabpro.selectorLabels" . | nindent 4 }}
    app: {{ include "collabpro.fullname" . }}-web
