// One-time (rerun-when-you-want-a-refresh) generator for the profile page's
// avatar picker. DiceBear (@dicebear/core + @dicebear/collection, CC0-
// licensed art) is only a devDependency - this script "dumps" its output to
// static SVG files under public/avatars/ at build/dev time, so the client
// bundle never imports DiceBear itself (a profile page that ships 50+
// character illustrations as inline data URIs in its JS bundle would be a
// real regression; static files are just normal cached <img> requests).
//
// Each output SVG is DiceBear's own illustration (untouched) plus a small
// animated gradient ring wrapped around it - the "premium, moves" part the
// avatars needed, without distorting the character art itself.
//
// Run: node scripts/generate-avatars.mjs
import { createAvatar } from '@dicebear/core';
import { notionists, shapes } from '@dicebear/collection';
import { mkdirSync, writeFileSync, rmSync, existsSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT_DIR = path.join(__dirname, '..', 'public', 'avatars');
const MANIFEST_PATH = path.join(__dirname, '..', 'lib', 'avatars.ts');

const COUNT_PER_STYLE = 30;

// On-brand background palette (matches the #6965db violet used throughout
// AI/MCP/editor UI, plus the app's existing accent colors) - DiceBear picks
// one per seed deterministically from this list instead of its own defaults.
const BACKGROUND_PALETTE = ['6965db', '0ea5e9', '10b981', 'f59e0b', 'f43f5e', '8b5cf6', '14b8a6', 'f97316'];

// Animated ring gradient pairs, cycled by index for variety across the set.
const RING_GRADIENTS = [
  ['#6965db', '#38bdf8'],
  ['#10b981', '#0ea5e9'],
  ['#f97316', '#ec4899'],
  ['#8b5cf6', '#d946ef'],
  ['#0ea5e9', '#6965db'],
  ['#f43f5e', '#f59e0b'],
  ['#64748b', '#0ea5e9'],
  ['#f59e0b', '#ef4444'],
];

function extractInner(svgString) {
  const viewBoxMatch = svgString.match(/viewBox="0 0 ([\d.]+) ([\d.]+)"/);
  const size = viewBoxMatch ? Number(viewBoxMatch[1]) : 100;
  const withoutMetadata = svgString.replace(/<metadata[\s\S]*?<\/metadata>/, '');
  const inner = withoutMetadata.replace(/^<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '');
  return { inner, size };
}

function buildAnimatedAvatarSvg(diceBearSvg, ringColors, spinDur) {
  const { inner, size } = extractInner(diceBearSvg);
  const scale = 96 / size;
  const [c1, c2] = ringColors;
  const gradId = `g${Math.abs(hashCode(ringColors.join('') + spinDur))}`;

  return `<svg viewBox="0 0 108 108" xmlns="http://www.w3.org/2000/svg">
<defs>
<linearGradient id="${gradId}" x1="0%" y1="0%" x2="100%" y2="100%">
<stop offset="0%" stop-color="${c1}"/>
<stop offset="100%" stop-color="${c2}"/>
</linearGradient>
</defs>
<circle cx="54" cy="54" r="52" fill="none" stroke="url(#${gradId})" stroke-width="3" stroke-linecap="round" stroke-dasharray="230 100" opacity="0.9">
<animateTransform attributeName="transform" type="rotate" from="0 54 54" to="360 54 54" dur="${spinDur}s" repeatCount="indefinite"/>
</circle>
<g transform="translate(6,6) scale(${scale})">${inner}</g>
</svg>`;
}

function hashCode(str) {
  let hash = 0;
  for (let i = 0; i < str.length; i++) hash = (hash << 5) - hash + str.charCodeAt(i);
  return hash;
}

function toTitle(s) {
  return s.replace(/[-_]/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
}

if (existsSync(OUT_DIR)) rmSync(OUT_DIR, { recursive: true });
mkdirSync(OUT_DIR, { recursive: true });

const STYLES = [
  { key: 'notionists', module: notionists, label: 'Notionists' },
  { key: 'shapes', module: shapes, label: 'Shapes' },
];

const manifestEntries = [];
let globalIndex = 0;

for (const { key, module, label } of STYLES) {
  for (let i = 1; i <= COUNT_PER_STYLE; i++) {
    const seed = `collabpro-${key}-${i}`;
    const diceBearSvg = createAvatar(module, {
      seed,
      backgroundColor: BACKGROUND_PALETTE,
      backgroundType: ['gradientLinear'],
      radius: 50,
    }).toString();

    const ringColors = RING_GRADIENTS[globalIndex % RING_GRADIENTS.length];
    const spinDur = 14 + (globalIndex % 5) * 2.5; // 14-24s, varies so the set doesn't spin in unison
    const finalSvg = buildAnimatedAvatarSvg(diceBearSvg, ringColors, spinDur);

    const id = `${key}-${i}`;
    const fileName = `${id}.svg`;
    writeFileSync(path.join(OUT_DIR, fileName), finalSvg, 'utf8');
    manifestEntries.push({ id, name: `${label} ${i}`, url: `/avatars/${fileName}` });
    globalIndex++;
  }
}

const manifestSource = `/**
 * Generated by scripts/generate-avatars.mjs - do not hand-edit.
 *
 * Profile page's "premium animated avatar" set: ${manifestEntries.length}
 * DiceBear (CC0-licensed) illustrations, pre-rendered to static SVG files
 * under public/avatars/ with an animated gradient ring wrapped around each
 * one. Static files, not embedded data URIs - DiceBear itself is only a
 * devDependency and never ships in the client bundle.
 */
export interface AvatarPreset {
  id: string;
  name: string;
  url: string;
}

export const AVATAR_PRESETS: AvatarPreset[] = ${JSON.stringify(manifestEntries, null, 2)};
`;

writeFileSync(MANIFEST_PATH, manifestSource, 'utf8');

console.log(`Generated ${manifestEntries.length} avatars into ${path.relative(process.cwd(), OUT_DIR)}/`);
console.log(`Wrote manifest to ${path.relative(process.cwd(), MANIFEST_PATH)}`);
