"use client"

import React, { useState, useEffect, useRef } from 'react';
import { 
  Sparkles, 
  X, 
  Send, 
  BrainCircuit, 
  FileText, 
  Layers, 
  Code, 
  HelpCircle,
  Activity,
  User,
  Zap,
  RefreshCw,
  PlusCircle,
  Check
} from 'lucide-react';
import { toast } from 'sonner';
import { api, useMutation } from '@/lib/state-sync/react';

interface AiSidebarProps {
  isOpen: boolean;
  onClose: () => void;
  fileId: string;
  fileData: any;
}

interface Message {
  sender: 'user' | 'ai';
  text: string;
  timestamp: string;
  actionType?: 'insert_text' | 'insert_shape';
  actionPayload?: string;
}

export default function AiSidebar({ isOpen, onClose, fileId, fileData }: AiSidebarProps) {
  const [messages, setMessages] = useState<Message[]>([
    {
      sender: 'ai',
      text: "👋 Hello! I am your CollabPro AI Co-Pilot. I can read your whiteboard canvas, suggest architectural components, and write structural markdown files live for you! How can I assist you today?",
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    }
  ]);
  const [input, setInput] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const [activeModel, setActiveModel] = useState('gpt-4o-mini');
  const chatEndRef = useRef<HTMLDivElement>(null);

  // Mutations to update document and canvas live!
  const updateDocument = useMutation(api.files.updateDocument);
  const updateWhiteboard = useMutation(api.files.updateWhiteboard);

  useEffect(() => {
    if (typeof window !== 'undefined') {
      const storedModel = localStorage.getItem('collabpro_ai_model');
      if (storedModel) {
        setActiveModel(storedModel);
      }
    }
  }, []);

  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, isTyping]);

  const handleSend = (textToSend: string) => {
    if (!textToSend.trim()) return;

    const userMsg: Message = {
      sender: 'user',
      text: textToSend,
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    };

    setMessages(prev => [...prev, userMsg]);
    setInput('');
    setIsTyping(true);

    // Simulate AI response logic
    setTimeout(() => {
      let aiResponseText = "I've processed your request. Let me help you compile or expand your visual blueprints!";
      let actionType: 'insert_text' | 'insert_shape' | undefined;
      let actionPayload: string | undefined;

      const lowerText = textToSend.toLowerCase();

      if (lowerText.includes('diagram') || lowerText.includes('analyze') || lowerText.includes('flowchart')) {
        aiResponseText = "📊 **Workspace Whiteboard Analysis:**\n\nI scanned the active board elements. Your workspace currently maps a collaborative flow containing coordinate components. Here is a suggested system model:\n\n• **Inbound router nodes** split traffic flow.\n• **Redis caching layer** handles state replication SLA.\n• **SQLite DB adapters** serve transactional schemas.";
        actionType = 'insert_shape';
        actionPayload = JSON.stringify([
          { type: 'rectangle', x: 250, y: 120, width: 140, height: 70, strokeColor: '#6965db', backgroundColor: 'transparent', strokeWidth: 2, roundness: true },
          { type: 'text', x: 270, y: 145, text: 'AI Service Node', fontSize: 13, fontFamily: 1 }
        ]);
      } else if (lowerText.includes('text') || lowerText.includes('markdown') || lowerText.includes('document')) {
        aiResponseText = "📝 **AI Text Blueprint Generator:**\n\nI've generated a premium engineering document draft summarizing system designs. You can append this blueprint block into the editor.";
        actionType = 'insert_text';
        actionPayload = "\n\n## 🛠️ System Design Blueprint\n*Generated by CollabPro AI Co-Pilot*\n\n### 🚀 High-Level Architecture\n1. **State-Sync Engine:** Delivers real-time collaborative updates.\n2. **pgBouncer Pooling:** Manages database concurrency SLA.\n3. **Redis Cache-Aside:** Resolves workspace lookups in < 5ms.\n";
      } else {
        aiResponseText = "I've structured a custom code snippet analysis block based on your request. Let me know if you would like me to append system details directly to your markdown file or inject a flowchart canvas node.";
      }

      const aiMsg: Message = {
        sender: 'ai',
        text: aiResponseText,
        timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
        actionType,
        actionPayload
      };

      setMessages(prev => [...prev, aiMsg]);
      setIsTyping(false);
    }, 1800);
  };

  const handleActionClick = (msg: Message) => {
    if (!msg.actionType || !msg.actionPayload) return;

    if (msg.actionType === 'insert_text') {
      const currentDoc = fileData?.document || '';
      const updatedDoc = currentDoc + msg.actionPayload;
      updateDocument({ _id: fileId, document: updatedDoc })
        .then(() => {
          toast.success("AI blueprint successfully appended into the document editor!");
        })
        .catch(() => {
          toast.error("Failed to append AI text block.");
        });
    } else if (msg.actionType === 'insert_shape') {
      let currentWhiteboard: any[] = [];
      if (fileData?.whiteboard) {
        try {
          currentWhiteboard = JSON.parse(fileData.whiteboard);
        } catch (e) {
          console.error(e);
        }
      }

      const newShapes = JSON.parse(msg.actionPayload);
      const updatedWhiteboard = [...currentWhiteboard, ...newShapes];
      updateWhiteboard({ _id: fileId, whiteboard: JSON.stringify(updatedWhiteboard) })
        .then(() => {
          toast.success("AI structural diagram nodes appended into the canvas board!");
        })
        .catch(() => {
          toast.error("Failed to inject canvas elements.");
        });
    }
  };

  if (!isOpen) return null;

  return (
    <div className="w-80 h-full bg-white dark:bg-slate-950 border-l border-slate-200/60 dark:border-slate-800/80 flex flex-col shrink-0 relative z-[100] font-sans">
      
      {/* Sidebar Header */}
      <div className="px-4 py-3.5 border-b border-slate-100 dark:border-slate-800/80 flex items-center justify-between shrink-0 bg-slate-50/50 dark:bg-slate-900/20">
        <div className="flex items-center gap-2">
          <Sparkles className="h-4 w-4 text-[#6965db] animate-pulse" />
          <div>
            <div className="text-[10px] font-bold text-slate-800 dark:text-slate-100">Co-Pilot Workspace</div>
            <div className="text-[8px] text-[#6965db] font-black uppercase tracking-wider mt-0.5 flex items-center gap-1">
              Active: {activeModel} <span className="h-1 w-1 bg-emerald-500 rounded-full animate-ping" />
            </div>
          </div>
        </div>
        <button 
          onClick={onClose}
          className="p-1 rounded-lg hover:bg-slate-100 dark:hover:bg-slate-900 text-slate-400 dark:text-slate-500 hover:text-slate-600 cursor-pointer transition-colors"
        >
          <X className="h-4 w-4" />
        </button>
      </div>

      {/* Preset Prompt Buttons Bar */}
      <div className="p-2 border-b border-slate-100 dark:border-slate-800/80 bg-slate-50/20 flex gap-1.5 overflow-x-auto shrink-0 select-none">
        <button
          onClick={() => handleSend("Analyze active Whiteboard Diagram elements")}
          className="px-2.5 py-1 bg-white dark:bg-slate-900 border border-slate-200/50 dark:border-slate-800 rounded-lg text-[8.5px] font-black uppercase tracking-wider text-slate-500 hover:border-[#6965db]/50 dark:hover:border-[#6965db]/50 hover:text-[#6965db] dark:hover:text-[#8572e3] cursor-pointer transition-all flex items-center gap-1 shrink-0"
        >
          <Layers className="h-3 w-3" /> Analyze Canvas
        </button>
        <button
          onClick={() => handleSend("Generate a system design markdown blueprint")}
          className="px-2.5 py-1 bg-white dark:bg-slate-900 border border-slate-200/50 dark:border-slate-800 rounded-lg text-[8.5px] font-black uppercase tracking-wider text-slate-500 hover:border-[#6965db]/50 dark:hover:border-[#6965db]/50 hover:text-[#6965db] dark:hover:text-[#8572e3] cursor-pointer transition-all flex items-center gap-1 shrink-0"
        >
          <FileText className="h-3 w-3" /> Insert Blueprint
        </button>
      </div>

      {/* Messages Scroll Panel */}
      <div className="flex-1 overflow-y-auto p-4 space-y-4 min-h-0 bg-slate-50/20">
        {messages.map((msg, i) => (
          <div key={i} className={`flex flex-col ${msg.sender === 'user' ? 'items-end' : 'items-start'}`}>
            <div className={`max-w-[85%] rounded-2xl p-3 text-[10px] leading-relaxed shadow-sm ${
              msg.sender === 'user' 
                ? 'bg-[#6965db] text-white rounded-br-none font-medium' 
                : 'bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 text-slate-700 dark:text-slate-300 rounded-bl-none'
            }`}>
              {/* Escape markdown paragraphs */}
              <div className="whitespace-pre-line font-sans prose dark:prose-invert">
                {msg.text}
              </div>

              {/* Quick action triggers */}
              {msg.actionType && msg.actionPayload && (
                <button
                  type="button"
                  onClick={() => handleActionClick(msg)}
                  className="mt-3 w-full h-7 bg-[#6965db]/10 dark:bg-[#6965db]/20 hover:bg-[#6965db] hover:text-white border border-[#6965db]/30 text-[#6965db] dark:text-[#8572e3] text-[8.5px] font-black uppercase tracking-wider rounded-lg flex items-center justify-center gap-1 transition-all cursor-pointer"
                >
                  <PlusCircle className="h-3 w-3" /> 
                  {msg.actionType === 'insert_text' ? 'Append to Document' : 'Insert AI Node Shape'}
                </button>
              )}
            </div>
            <span className="text-[7.5px] text-slate-400 dark:text-slate-500 mt-1 px-1">{msg.timestamp}</span>
          </div>
        ))}

        {isTyping && (
          <div className="flex flex-col items-start">
            <div className="bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-2xl rounded-bl-none p-3 shadow-sm flex items-center gap-2">
              <span className="h-1.5 w-1.5 bg-slate-400 rounded-full animate-bounce" style={{ animationDelay: '0ms' }} />
              <span className="h-1.5 w-1.5 bg-slate-400 rounded-full animate-bounce" style={{ animationDelay: '150ms' }} />
              <span className="h-1.5 w-1.5 bg-slate-400 rounded-full animate-bounce" style={{ animationDelay: '300ms' }} />
            </div>
          </div>
        )}
        <div ref={chatEndRef} />
      </div>

      {/* Input controls footer */}
      <div className="p-3.5 border-t border-slate-100 dark:border-slate-800/80 shrink-0 bg-slate-50/30">
        <div className="flex items-center gap-2 bg-white dark:bg-slate-900 border border-slate-200/50 dark:border-slate-800 rounded-xl px-3 py-1.5 shadow-xs focus-within:border-[#6965db]/80">
          <input
            type="text"
            placeholder="Ask your AI companion..."
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={(e) => e.key === 'Enter' && handleSend(input)}
            className="flex-1 bg-transparent border-0 focus:outline-none focus:ring-0 text-[10px] text-slate-700 dark:text-slate-200 placeholder-slate-400"
          />
          <button
            type="button"
            onClick={() => handleSend(input)}
            className="p-1.5 rounded-lg bg-[#6965db] hover:bg-[#5753c9] text-white cursor-pointer transition-colors"
          >
            <Send className="h-3.5 w-3.5" />
          </button>
        </div>
      </div>

    </div>
  );
}
